apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-worker-deployment
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
      - name: worker
        image: shatsberg/multi-worker
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS-PORT
            value: '6379'
