{{- if .Values.postgres.enabled}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "fib-calc.fullname" .}}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
      {{ include "fib-calc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: postgres
      {{ include "fib-calc.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{include "fib-calc.fullname" .}}-pg-data
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
            subPath: postgres
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: {{ include "fib-calc.fullname" . }}-postgres-creds
                  key: PGPASSWORD
{{- end}}