{{- if .Values.postgres.enabled}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{include "fib-calc.fullname" .}}-pg-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{end}}