{{- if .Values.postgres.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fib-calc.fullname" . }}-postgres-creds
data:
  PGUSER: {{ print "postgres" | b64enc }}
  PGHOST: {{ include "fib-calc.fullname" . |printf "%s-postgres" | b64enc }}
  PGPORT: {{print "5432" | b64enc }}
  PGDATABASE: {{"postgres" | b64enc}}
  PGPASSWORD: {{ randAlphaNum 32 | b64enc }}
{{- end}}