{{- if .Values.postgres.enabled}}

apiVersion: v1
kind: Service
metadata:
  name: {{include "fib-calc.fullname" .}}-postgres
spec:
  type: ClusterIP
  selector:
    component: postgres
    {{ include "fib-calc.selectorLabels" . | nindent 4 }}

  ports:
  - port: 5432
    targetPort: 5432
{{- end}}