apiVersion: v1
kind: Service
metadata:
  name: {{ include "fib-calc.fullname" . }}-server
spec:
  type: ClusterIP
  selector:
    component: server
    {{ include "fib-calc.selectorLabels" . | nindent 4}}
  ports:
  - port: 5000
    targetPort: 5000
