{{- if .Values.redis.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fib-calc.fullname" .}}-redis
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
        {{ include "fib-calc.selectorLabels" . | nindent 6  }}
      
  template:
    metadata:
      labels:
        component: redis
        {{ include "fib-calc.labels" . | nindent 8  }}
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
{{- end}}