{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fib-calc.fullname" . }}-redis
spec:
  type: ClusterIP
  selector:
    component: redis
    {{ include "fib-calc.selectorLabels" . | nindent 4 }}
  ports:
  - port: 6379
    targetPort: 6379
{{- end}}