client:
  image:
    tag: latest
  replicas: 1
server:
  image:
    tag: '89'
  replicas: 2
worker:
  image:
    tag: latest
  replicas: 1
redis:
  enabled: true
  credConfigMap: ''
postgres:
  enabled: true
  credSecret: ''
ingress:
  enabled: true
  hostnmae: fib.localhost
